#!/bin/sh
# Should generate the standalone ndk toolchain by : $NDK/build/tools/make-standalone-toolchain.sh --platform=android-8 --install-dir="your standalone ndk location"
# Should set the TOOLCHAIN_PATH param to YOUR STANDALONE NDK LOCATION generated by make-standalone-toolchain.sh
TOOLCHAIN_PATH=/Users/lovekoala/android_standalone_tools
# Add the TOOLCHAIN_PATH/bin to the PATH environment
export PATH=$PATH:$TOOLCHAIN_PATH/bin
make -f Makefile_android
